---
- name: installing httpd and opening port 80, start the service and create a user
  hosts: web_servers
  become: true
  
  tasks:

  - name: installing httpd
    yum: 
      name: "{{ http_package }}"
      state: latest

  - name: opening port 80
    firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled
      immediate: yes 

  - name: starting and enabling httpd
    service:
      name: "{{ http_package }}"
      state: started
      enabled: yes

  - name: create a user
    user: 
      name: john
      comment: john Doe
      group: wheel
      password: "{{ pass }}"
      
